source 'https://rubygems.org'

gem 'active_hash'
gem 'bourbon'
gem 'coffee-rails', '~> 4.0.0'
gem 'devise'
gem 'foundation-rails'
gem 'friendly_id', '~> 5.0.0'
gem 'haml'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'local_time'
gem 'pg'
gem 'rails', '4.1.6'
gem 'sass-rails', '~> 4.0.3'
gem 'thin'
gem 'turbolinks'
gem 'redcarpet'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'simple_form'
gem 'spring',        group: :development
gem 'stamp'

gem 'uglifier', '>= 1.3.0'
gem 'validate_url'
